source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "webrick", "~> 1.7"
gem "jekyll-remote-theme"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-include-cache"
